apiVersion: v1
kind: Pod
metadata:
  name: matchbox-pod
spec:
  containers:
  - image: matchbox-docimg
    name: matchbox-container
    imagePullPolicy: IfNotPresent
    env: 
    - name: EXOMISER_DATA_DIR
      value: "/Exomiser/matchbox/data/exomiser-cli-8.0.0/data"
    - name: MONGODB_HOSTNAME
      value: ""
    - name: MONGODB_PORT
      value: "27017"
    - name: MONGODB_USERNAME
      value: ""
    - name: MONGODB_PASSWORD
      value: ""
    - name: MONGODB_DATABASE
      value: "mme_primary"